Fix -Werror=catch-value and a few missing issues
fix -Werror=catch-value as below and a few missing ones
*******************************************************
MediaSDK/_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp:2148:20:
error: catching polymorphic type ‘class std::bad_alloc’ by value [-Werror=catch-value=]
         catch(std::bad_alloc)

Signed-off-by: jwang <jing.j.wang@intel.com>